services:
  db:
    image: postgres:16
    container_name: mrsimon-file-system-db

    restart: unless-stopped

    environment:
      POSTGRES_DB: mrsimon_file_system
      POSTGRES_USER: mrsimon
      POSTGRES_PASSWORD: mrsimon_password

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: